/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/6.4.1/userguide/multi_project_builds.html
 */

rootProject.name = "worker_service"
pluginManagement {
    plugins {
        id("org.jetbrains.kotlin.jvm") version "1.6.20"
    }
}

include("CoreServiceKit")
project(":CoreServiceKit").projectDir =  File(settingsDir, "../core_service_kit")

